<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitac60fb544ce92be309d8e16f1c58983c
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitac60fb544ce92be309d8e16f1c58983c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitac60fb544ce92be309d8e16f1c58983c::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitac60fb544ce92be309d8e16f1c58983c::$classMap;

        }, null, ClassLoader::class);
    }
}
